from sqlalchemy.orm import Session
from ..models import AutopilotConfig, Job, Resume, Application
from ..services.scraper import fetch_jobs
from ..services.embedding import embedding_service
from ..services.matcher import compute_fit_score
from ..services.llm_agent import generate_cover_letter
from datetime import datetime
import logging

logger = logging.getLogger(__name__)

def run_autopilot(db: Session):
    """Executed by scheduler: process all active autopilot configs."""
    configs = db.query(AutopilotConfig).filter(AutopilotConfig.is_active == True).all()
    if not configs:
        logger.info("No active autopilot configurations.")
        return

    # 1. Fetch new jobs once (shared across configs)
    new_jobs_data = fetch_jobs(limit=20)
    added_job_ids = []
    for job_dict in new_jobs_data:
        existing = db.query(Job).filter(Job.external_id == job_dict["external_id"]).first()
        if not existing:
            embedding = embedding_service.encode_single(job_dict["description"])
            job = Job(**job_dict, embedding=embedding)
            db.add(job)
            db.flush()
            added_job_ids.append(job.id)
    db.commit()
    logger.info(f"Fetched {len(new_jobs_data)} jobs, added {len(added_job_ids)} new ones.")

    # 2. For each active config, process jobs
    for config in configs:
        resume = db.query(Resume).filter(Resume.id == config.resume_id).first()
        if not resume or not resume.embedding:
            logger.warning(f"Resume {config.resume_id} not ready for autopilot.")
            continue

        # Get jobs without an application from this resume
        existing_app_job_ids = db.query(Application.job_id).filter(
            Application.resume_id == config.resume_id
        ).subquery()
        eligible_jobs = db.query(Job).filter(
            Job.id.not_in(existing_app_job_ids)
        ).order_by(Job.created_at.desc()).limit(config.max_applications_per_run * 2).all()

        applications_created = 0
        for job in eligible_jobs:
            if applications_created >= config.max_applications_per_run:
                break

            score = compute_fit_score(resume.embedding, job.embedding)
            if score >= config.fit_threshold:
                try:
                    llm_response = generate_cover_letter(job.description, resume.raw_text)
                    cover_letter = llm_response.cover_letter
                except Exception as e:
                    logger.error(f"LLM generation failed for job {job.id}: {e}")
                    continue

                app = Application(
                    job_id=job.id,
                    resume_id=config.resume_id,
                    fit_score=score,
                    cover_letter=cover_letter,
                    status="draft",
                    applied_at=datetime.utcnow(),
                    notes="Auto-generated by Autopilot"
                )
                db.add(app)
                applications_created += 1

        db.commit()
        logger.info(f"Autopilot for resume {config.resume_id}: created {applications_created} applications.")